### ISSUE TITLE
Add Static Data to a separate file

### ISSUE THREAD

**Issue by barbier** [MinisterioPublicoRJ/inLoco-2.0#348]
On production build, the following message is logged on console:
"[BABEL] Note: The code generator has deoptimised the styling of (...) as it exceeds the max of "500KB"."

The message is logged twice, pointing two files of static data on /src/components/App/mocks, maybe these files are disturbing the optimization of the application and should be on a separate file?

**Comment by rlage** [comment]
The two messages are related to placesMock.js and layersMock.js.

placesMock is needed. layersMock isn't. We should remove layersMock But they are already separate files.

As for placesMock, we could just copy to the static folder and remove from normal webpack build and optimization hocus pocus. Maybe just copy as we do with copy_modules and copy_static (it could be here, because it is, indeed, static).
