### ISSUE TITLE
Exported image opacity doesn't have transparency

### ISSUE THREAD

**Issue by nighto** [MinisterioPublicoRJ/inLoco-2.0#358]
When exporting the map as image, the generated image has the dark background (transparent black) as opaque black.

@mcastre do you think it is a known limitation of html2canvas?

![image](https://user-images.githubusercontent.com/397851/31239675-5520aad2-a9d4-11e7-919a-86e48cb3cff7.png)

![mp_em_mapas 1](https://user-images.githubusercontent.com/397851/31239678-597776e2-a9d4-11e7-9913-0e14bb4e2223.png)

**Comment by barbier** [comment]
I think the problem it's because the image originally it's "pure black" `rgba(255,255,255,1)` and the opacity of the parent element is manipulated on the application. I'll try to change both opacities and put it back after exporting, okay?
![image](https://user-images.githubusercontent.com/1870079/31285867-dc09df1e-aa92-11e7-9a9b-9fbcbc0cf94e.png)
